[project]
name = "pytest-demo"
version = "0.1.0"
dependencies = [
    "cryptography==3.2.1",
    "requests==2.20.0", 
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["src"]  # Critical: Add src to Python path
